spring:
  datasource:
    url: "jdbc:h2:file:./recipes"
  jpa:
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      path: "/console"

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 6745e625c7801b71fd17
            clientSecret: 7875f3020f80d97f5a63917a45968bc6eafc8f1f
            scope:
              - user:email
              - read:user
          facebook:
            clientId: 305411277731406
            clientSecret: 1f783a0553c9fbdcd9c668d233bca787
            scope:
              - email
              - public_profile
