spring:
  datasource:
    url: "jdbc:h2:file:./recipes"
  jpa:
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      path: "/console"

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 20451036798bd6de40f5
            clientSecret: 55a3fbcc7037924137b214f53f6c2dc5248c4c45
            scope:
              - user:email
              - read:user
          facebook:
            clientId: 305411277731406
            clientSecret: 1f783a0553c9fbdcd9c668d233bca787
            scope:
              - email
              - public_profile
